name: EduHub
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_database: ^11.1.0
  firebase_storage: ^12.2.0
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  firebase_messaging: ^15.1.0
  intl_phone_field: ^3.2.0
  google_sign_in: ^6.2.1
  animated_text_kit: ^4.2.2
  cloud_firestore: ^5.3.0
  image_picker: ^1.1.2
  video_player: ^2.9.1
  intl: ^0.19.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Adding the logo in the assets section
  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/EDU-HUB logo copy.png"
